#pragma once

enum class ObjectID : uint8_t {
    Chaser		    = 0,
    Crumbs		    = 1,
    DiaPlatform		= 2,
    Diamond		    = 3,
    Door		    = 4,
    Finish		    = 5,
    Floor		    = 6,
    Fuel		    = 7,
    Hole		    = 8,
    Iceman		    = 9,
    JetPack		    = 10,
    Key		        = 11,
    Ladder		    = 12,
    Message		    = 13,
    Pillar		    = 14,
    Platform	    = 15,
    Portal		    = 16,
    Ramp		    = 17,
    Shield		    = 18,
    Slingshot	    = 19,
    Start		    = 20,
    Teleport	    = 21,
    TriPlatform 	= 22,
    TriWall		    = 23,
    Wall		    = 24,
    NUM_OBJECTS     = 25,
    
    Theme		    = 250,
    Weather		    = 251,
    Music		    = 252,
    Unknown		    = 253,
};